namespace PersistenceLayer.DataAccess.Entities.Core;

using PersistenceLayer.DataAccess.Entities.Identity;

/// <summary>
/// Represents a translation record submitted or received by a user.
/// </summary>
public class TranslationEntity
{
    /// <summary>
    /// Gets the unique ID of the translation.
    /// </summary>
    public int Id { get; init; }

    /// <summary>
    /// Gets or sets the ID of the user who submitted the translation.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Gets the original text to be translated.
    /// </summary>
    public string OriginalText { get; init; } = default!;

    /// <summary>
    /// Gets the translated version of the original text.
    /// </summary>
    public string TranslatedText { get; init; } = default!;

    /// <summary>
    /// Gets the source language of the original text.
    /// </summary>
    public string SourceLanguage { get; init; } = default!;

    /// <summary>
    /// Gets the target language for the translation.
    /// </summary>
    public string TargetLanguage { get; init; } = default!;

    /// <summary>
    /// Gets the date when the translation was last requested.
    /// </summary>
    public DateTime? LastRequestedAt { get; init; }

    /// <summary>
    /// Gets how many times this translation was requested.
    /// </summary>
    public int RequestCount { get; init; }

    /// <summary>
    /// Gets or sets the ranking score of the translation.
    /// </summary>
    public int Ranking { get; set; }

    /// <summary>
    /// Gets the date when the translation was created.
    /// </summary>
    public DateTime CreatedAt { get; init; }

    /// <summary>
    /// Gets the date when the translation was last updated.
    /// </summary>
    public DateTime? UpdatedAt { get; init; }

    /// <summary>
    /// Gets a value indicating whether the translation was generated by AI.
    /// </summary>
    public bool IsAiGenerated { get; init; }

    /// <summary>
    /// Gets a value indicating whether the translation is verified.
    /// </summary>
    public bool IsVerified { get; init; }

    /// <summary>
    /// Gets a value indicating whether the translation is marked as deleted.
    /// </summary>
    public bool IsDeleted { get; init; }

    /// <summary>
    /// Gets a value indicating whether the translation is marked as a favorite.
    /// </summary>
    public bool IsFavorite { get; init; }

    /// <summary>
    /// Gets the associated user entity.
    /// </summary>
    public UserEntity User { get; init; } = default!;

    /// <summary>
    /// Gets the  top translations that reference this translation.
    /// </summary>
    public TopTranslationEntity? TopTranslation { get; init; }
}