name: Build and Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ story/**, task/**, bug/** ]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore Backend/lb-translator.sln

      - name: Build solution
        run: dotnet build Backend/lb-translator.sln --no-restore

      - name: Run tests
        run: dotnet test Backend/lb-translator.sln --no-build --verbosity normal

      - name: Check formatting
        run: dotnet format Backend/lb-translator.sln --verify-no-changes
