name: Build and Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ story/**, task/**, bug/** ]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore Backend/ASP.Core.sln

      - name: Build solution
        run: dotnet build Backend/ASP.Core.sln --no-restore --configuration Release

      - name: Run all tests
        run: dotnet test Backend/ASP.Core.sln --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --configuration Release


      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/TestResults/*.trx'

      - name: Check code formatting
        run: dotnet format Backend/ASP.Core.sln --verify-no-changes --verbosity diagnostic
